### ISSUE TITLE
The u-boot image for tl-wr841n v10 is missing

### ISSUE THREAD

**Issue by oszilloskop** [CodeFetch/router-u-boot#1]
I can't find a u-boot Image for the tl-wr841n v10 router in your repo.

**Comment by CodeFetch** [comment]
Thanks for the info!

**Comment by CodeFetch** [comment]
Fixed in https://github.com/CodeFetch/router-u-boot/commit/5f971aaeb72796631fd53a6984c74a8dc256c176
