### ISSUE TITLE
hard mod double flash

### ISSUE THREAD

**Issue by youxiaojie** [CodeFetch/router-u-boot#10]
thanks for your patience.and if i I hard hardmod my router 8M flash to 16M  put art to the last 64kB at the end of 16MiB does openwrt uboot recognize it? do i need to change env mtd part ?and if I double my memory uboot can deal with it?

**Comment by CodeFetch** [comment]
For TP-Link devices OpenWrt and this bootloader automatically detect the flash size. It is safe to upgrade to 16 MiB. Please be aware that you also need to copy the MAC address as it is not in the ART partition on TP-Link devices. 

https://camo.githubusercontent.com/a7c92d54bb325b623f64dc5b53c6df3c1935237a/687474703a2f2f7777772e746563682d626c6f672e706c2f776f726470726573732f77702d636f6e74656e742f75706c6f6164732f323031362f30332f6d72333032305f752d626f6f742d6d6f64696669636174696f6e5f666c6173682d6d61705f636f6d70617269736f6e2e706e67
