### ISSUE TITLE
i see qca9558 often connect with ar8327 what is 8327's driver? 

### ISSUE THREAD

**Issue by youxiaojie** [CodeFetch/router-u-boot#11]
1.I see there are phy drivers like s17 s27 8033 which one is used with 8327? and what if use internal 100m switch? 
2.9558 can init ram using qca dram?but 9561 can not interesting. why? or there is other question?
3.can this uboot load kernel from foreign usb disk?if so I can run as linux freebsd mips machine. 20years ago I learn mips from course computer archetecture.  if this uboot load kernel from usb and make usb as root, it is a mips machine.

**Comment by CodeFetch** [comment]
As far as I know there are only two very different switch configurations (s17 and s26) and we don't use any special functionalities of the switches. Therefore the switch driver is quite generic. Unfortunately I don't remember what the differences between s17 and s26 were... Take this for example:

`	@$(call define_add,CONFIG_ATHRS17_PHY,1)`
It is a s17 switch
`	@$(call define_add,CONFIG_ATHRS_GMAC_SGMII,1)`
The GMAC is connected using SGMII
`	@$(call define_add,CFG_ATH_GMAC_NMACS,2)`
It has two GMACs

For getting it running there is no more magic. Knowing what chip is being used, helps you find out about the possible interface configuration (RGMII/SGMII/SerDes). Adding support for a router is more like knowing how the chips have been configured and interfaced with each other. For your Archer C7 everything you need has been contributed by psyborg already.

Edit: If you're interested in learning what these chips do: https://github.com/Deoptim/atheros
