### ISSUE TITLE
does it support tp archer c7 qca9558 + ar8327n?so clled ap136/ ap135?

### ISSUE THREAD

**Issue by youxiaojie** [CodeFetch/router-u-boot#6]
does it support tp archer c7 qca9558 + ar8327n? so clled ap136/ ap135? Do I need to modify files such as gpios according to original tp uboot, especially reset button and each leds like the previous commits to add a new device?

**Comment by youxiaojie** [comment]
does it support tp archer c7 qca9558 + ar8327n? so clled ap136/ ap135?

**Comment by CodeFetch** [comment]
The Archer C7 has different hardware revisions. I'm not sure. This one does support v1: https://github.com/psyborg55/u-boot_mod/. The other versions seem to be very similar. Thus I guess you don't need big changes to get your version running if it differs.

**Comment by youxiaojie** [comment]
need I port archer C7 to your line?
