### ISSUE TITLE
Writable environment variables

### ISSUE THREAD

**Issue by youxiaojie** [CodeFetch/router-u-boot#7]
I see most of tp link router has readonly env. can we make an u-boot env mtd to make env read/write? and I see they all 64kb, could it be changed to  128 kb or more? 
```
Writable environment variables

U-Boot uses special "environment variables" which are used for storing values of many different settings, like IP addresses of device and remote server for TFTP transaction, serial console baud rate, boot command, etc. Environment is usually stored in separate FLASH sector or its part, so all changes can be saved permanently.

None of the popular manufacturers provides this feature and use so called "read-only environment" (embedded in U-Boot image), which means that all changes made during a runtime will be lost after device restart and there is no way to store them in FLASH.

This modification uses writable environment variables in almost all supported devices, so you can do for example:


```

**Comment by CodeFetch** [comment]
Sure, it is an ordinary u-boot-env partition. You need to define the partition in the OpenWrt device tree file and then add the model to the supported list https://github.com/openwrt/openwrt/blob/master/package/boot/uboot-envtools/files/ath79 to be able to read/write the partition from OpenWrt.

EDIT: Yes, it could be changed to more than 64 kB, but it really is not needed. I guess we don't use a single kB at the moment... Many routers have a reserved space of 64 kB for environment variables even though the functionality is disabled in production bootloaders.
