### ISSUE TITLE
overclock of qca9580?

### ISSUE THREAD

**Issue by youxiaojie** [CodeFetch/router-u-boot#8]
in u-boot/include/soc/qca_pll_list.h
could I use this pll setup to overclock?

**Comment by CodeFetch** [comment]
Yes, but please use this fork https://github.com/psyborg55/u-boot_mod/.
You can set the profiles in U-Boot with `setclk`, but I don't know which one will work. If it doesn't boot, just hold the reset button pressed so that it will use safe clocks.
